### PR TITLE
Allow OctoPack to be installed by convention

### PR DESCRIPTION
**Pull request by tothegills**
Based on https://github.com/OctopusDeploy/OctoPack/pull/85

For NuGet versions that support it, OctoPack will be installed by the `\build` convention rather than by running `\tools\Install.ps1`.

This supports installing OctoPack into projects running NuGet 3.x with a `project.json`. file.

### CODE REVIEW

**Comment by johnkors** [comment]
`project.json` is dying. Maybe a `msbuild` version?

**Comment by robv8r** [comment]
I was just about to start work on the exact same issue.  PowerShell install scripts were always clunky and props and targets files always seemed more natural.  Do you mind if I review what you've done and make observations?

Also, do the project owners have a minimum .Net Framework (or netstandard) they support?  

Do we need to continue supporting .Net 3.5 and nuget 2.x?

**Comment by johnkors** [comment]
Seems they want to keep `OctoPack` as we know it, based on the non-responses here.

How about forking it and creating two seperate packages for this?:
`OctoPack.ProjectJson`
`OctoPack.MsBuild`

**Comment by robv8r** [comment]
I'm in favor of a modern approach to NuGet packaging.  I think we can add support for NuGet 3.5+ NuSpec's, project.json and MSBuild (v4.0+) while also continuing to support older NuGet and MSBuild older than v4.0 in the same package.  

I'd have to do some research in regards to [TFM](https://docs.nuget.org/ndocs/schema/target-frameworks) behavior in older NuGet packages and then determine where NuGet started supporting netstandard in favor of dotnet and dnx.

I also think we could support these without PowerShell scripts.  I may be a bit naive, but there has to be a way to add props, targets, and reference task assemblies without PowerShell, even for older versions of VS.

**Comment by robpearson** [comment]
Hey Everyone.  I'm really sorry as I haven't progressed this.  It's needed testing and I haven't completed a thorough review.  That said, we're planning to review and action this early in the new year.

**Comment by tothegills** [comment]
[Installing OctoPack via convention](https://trello.com/c/Hn71qhjl/97-installing-octopack-via-convention)

**Pull request merged**
