### PR TITLE
Option to force OctoPack to use file version

### PR DESCRIPTION
**Pull request by FabianTrottmann**
When using gitflow with git versioning task, OctoPack is not able to create nuget packages cause of the invalid version number (e.g. 1.5.0-unstable.94+94.Branch.develop.Sha.a.......). OctoPack uses by default the product version. The only way to overrule this, is to set the version with OctoPackPackageVersion. This PR adds an option to force OctoPack to use the file version.

### CODE REVIEW

**Comment by josteink** [comment]
Not commenting on the rest of the PR, this looks like a ripe candidate for squashing the commits :)

**Comment by caioproiete** [comment]
+1 for adding an option to tell OctoPack which version to use.

I've also opened PR #72 that validates if `ProductVersion` is a valid semantic version before using it (and therefore, will use `AssemblyVersion` if `ProductVersion` is not a valid semver)

[Do not use InformationalVersion/ProductVersion if not valid SemVer](https://github.com/OctopusDeploy/OctoPack/pull/72)

**Comment by FabianTrottmann** [comment]
+1 for checking if the product version is semver compatible and use implicitly the Assembly Version if its not

**Comment by jpflum** [comment]
+1 for adding an option to be able to use AssemblyFileVersion

**Comment by luke-barnett** [comment]
-1

I don't see the value in this over a combination of the following PRs

https://github.com/OctopusDeploy/OctoPack/pull/69

Which adds direct support of referencing the nuget version from git version

https://github.com/OctopusDeploy/OctoPack/pull/72

Which allows for a fallback to assembly version if the file version isn't valid semver.

**Comment by josteink** [comment]
A quick rebudge of that: As far as I see, #69 relies on people using git. We'd all love to, but some people are stuck using more antiquated source control systems. And having package-versioning tied to source-control system used seems like a strange and unnatural coupling, which should be avoided at all cost if it can.

#72 falls back to `AssemblyVersion`, not `Assembly`**`File`**`Version`.Some people use AssemblyFileVersion to version their products, and right now OctoPack provides no simple way of using this attribute. Sans forking.

This PR is about enabling use who don't use Git and use AssemblyFileVersion as the authoritative version-attribute, to use official Octopack instead of maintaining forks.

It's absolutely ridiculous that this feature request has taken so much time, and still isn't implemented.

cc: @PaulStovell Can you please take a look at this? Get some things in motion?

**Comment by asbjornu** [comment]
@josteink:
> having package-versioning strictly tied to source-control system used seems like a strange and unnatural coupling, which should be avoided at all cost.

That's the strangest thing I've read in a while. I'd say the contrary: There's nothing more natural than deducing a version number from your SCM, especially if you're using a (highly recommended) flow such as Git Flow or GitHubFlow.

If the version number of your package has absolutely no relation to your SCM, then how you use your SCM has no relation to your development process, which probably mean you have no process at all, which is be a pretty fat warning sign that you're Not Doing It Right.

That said, I agree that it's value in merging this PR as well as #69 and #72, since as you state; not everyone is using Git (although they should). :wink:

**Comment by asbjornu** [comment]
I've created [the following help request](http://help.octopusdeploy.com/discussions/problems/46085-please-stop-brainlessly-using-assemblyinformationalversion-in-octopack) to hopefully draw attention to this pull request and get it resolved. Please weigh in on the discussion in the Octopus Deploy Help forums where I believe the fine people at Octopus Deploy are more active than they are here on GitHub.

**Comment by josteink** [comment]
Thanks for raising the issue there. Commented and tried to put some weight on it.

**Pull request merged**
