### PR TITLE
[do not merge] Support NuGet 3.x and project.json

### PR DESCRIPTION
**Pull request by asizikov**
## What is this PullRequest about
When one is trying to use `Octopack` with NuGet 3.x and `project.json` file current setup will not work.

Based on NuGet 3.3 [documentation](https://docs.nuget.org/create/creating-and-publishing-a-package)

>Install.ps1 runs when a package is installed in a project.
>
>[NuGet 3.x] This script **will not be executed in projects managed by project.json**

However: 

>**Import MSBuild targets and props files into project**
>
>A new convention has been added to the structure of NuGet packages. 
As a peer to `\lib`, `\content`, and `\tools`, you can now include a `\build` folder in your package. 
Under this folder, you can place two files with fixed names, `{packageid}.targets` or `{packageid}.props`. 
These two files can be either directly under `\build` or under framework-specific folders just like the other folders. The rule for picking the best-matched framework folder is exactly the same as in those.

Technically there is no need for `Install.ps1`. 

>When NuGet installs a package with `\build` files, it will add an MSBuild element in the project file pointing 
to the `.targets` and `.props` files. The `.props` file is added at the top, whereas the `.targets` file is added to the bottom.

That will only work when one is using NuGet 2.5 or above. 
I deleted `Install.ps1` and `Uninstall.ps1` but they can be reverted to point to new `\build` folder for backward compatibility. 
I'm not sure if that's a good idea, though.

## Plan

I can see the migration as a few steps process:

* Modify `build.ps1` to `tools` content into `\build` folder
* Modify `.nuspec` file to copy `build\*` content into `build` target
* Delete `Install.ps1` and `Uninstall.ps1` files

## Implementation

`build.ps1`
```diff
-    mkdir .\build\tools
-    dir -recurse .\source\OctoPack.Tasks\bin\$configuration | copy -destination build\tools -Force
-    dir -recurse .\source\tools | copy -destination build\tools -Force
+    mkdir .\build\build
+    dir -recurse .\source\OctoPack.Tasks\bin\$configuration | copy -destination build\build -Force
+    dir -recurse .\source\tools | copy -destination build\build -Force
```

`Octopack.nuspec`
```diff
-    <file src="tools\*" target="tools" />
+    <file src="build\*" target="build" />
```

There was already a similar [PR](https://github.com/OctopusDeploy/OctoPack/pull/64), but it had a couple of formatting issues and seems to be abandoned now.

## How to test

Well, that's a tricky question. Honestly, I can't come up with a nice integration test. And I see the test as a redundant here.
It will not test `OctoPack` but it will test `NuGet`. And it should already be covered by NuGet [tests](https://github.com/NuGet/NuGet.Client/tree/dev/test).

What I did: 
* Built package with `build.ps1`
* Deployed it to the temporary NuGet feed
* Installed it via NuGet 3 UI
* Executed MSBuild command in the same folder

``"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:RunOctoPack=true``

and got the desired message :)

> OctoPack: OctoPack successful

Please let me know if there is anything that I can improve.

## Progress

- [x] Sync with remote, resolve conflicts
- [ ] Make sure that NuGet 2.xx is still supported

### CODE REVIEW

**Comment by johnkors** [comment]
```
Starting with NuGet 3.4.2, -Source is a mandatory parameter unless DefaultPushSource config value is set in the NuGet config file.
nuget push foo.nupkg 4003d786-cc37-4004-bfdf-c4f3e8ef9b3a -Source https://www.nuget.org/api/v2/package
```

This target is only supplying `-s` as what I presume is `-Source`, no?

https://github.com/OctopusDeploy/OctoPack/blob/master/source/tools/OctoPack.targets#L108

**Comment by tothegills** [comment]
Hi @asizikov,

Thanks for the PR.  Sorry for taking so long to review.

I like the idea but unfortunately we need to support compatibility with older versions of NuGet.  Your comment:

> I deleted Install.ps1 and Uninstall.ps1 but they can be reverted to point to new \build folder for backwards compatibility. 
> I'm not sure if that's a good idea though.

This might be enough to maintain compatibility but we need to ensure that if we make this change it will work with all supported versions of NuGet.

Thanks again.

**Comment by asizikov** [comment]
@tothegills thanks for the review, tbh I've already forgotten about this PR :)
If you're interested in it, I can update it and test the compatibility with older NuGet versions.

**Comment by tothegills** [comment]
Hi,

There are a few other people who would appreciate the functionality you have implemented.  If you are willing to update this PR and check compatibility with older NuGet versions we will test and merge it and I'm sure you will get many thanks. :)  If there is anything I can do to help get it across the line please let me know.

Cheers

**Comment by asizikov** [comment]
@tothegills yes, I am willing to continue. Will try to find time on the weekend or during the next week.

**Comment by asizikov** [comment]
@tothegills I think, I'll have to drop this PR, as it's too outdated, contribution guidelines has changed. Also there are unnecessary merge conflicts in it. 
I created a new branch from the latest master and moved my work to #85 . Please close this one, take a look at the new one and let me know if there is anything else that I can do.

**Comment by tothegills** [comment]
Thank you @asizikov 
It's our fault for leaving these PRs so long to review.  I'll will ensure your other PR is compatible with NuGet 2 and get it merged.

**Pull request closed without merging**
