### PR TITLE
refine get assembly version task

### PR DESCRIPTION
**Pull request by dpvreony**
we spotted an issue where when you had an AssemblyVersion and AssemblyFileVersion the logic would select the AssemblyVersion. The PR now chooses on priority of

* Informational Product Version
* Assembly File Version
* Assembly Version

Thanks

### CODE REVIEW

**Comment by josteink** [comment]
We're maintaining a inhouse fork of OctoPack just because we prefer to use file-version for package-versioning. If we can get a good, configurable story for which version should be used, we wouldn't have to.

So far this looks like a step in the right direction :)

**Comment by baronfel** [comment]
We also have a fork for this reason.  It'd be great to get back to mainline!

**Comment by PoyaManouchehri** [comment]
Any word on this? We also have a similar need.

**Comment by DamianMac** [comment]
Sorry guys, we've not been giving this much love over the past few months with 3.0 taking all of our attention. We're sitting down next week to look at PRs for OctoPack

**Comment by martinheg** [comment]
Would also like to see this PR make it in soon for same reasons as others above.

**Comment by JoelHT-Landmark** [comment]
I'm voting for this too - as it enables simple compatibility with NuGet.PackageNPublish templated NuSpec files.

**Comment by dpvreony** [comment]
looks like no longer needed.

**Pull request closed without merging**
